### PR TITLE
task/runner: Handle extra import request errs when humanizing

### LINKED ISSUE #103: Improve handling of Catalyst error messages for inaccessible file when humanizing
[This check](https://github.com/livepeer/task-runner/blob/044f2766574bbc04255cdf8b28b1adbd06e7ffa6/task/runner.go#L479) needs to be able to handle the scenario where Catalyst retries and fails with a message like `Get "https://lens.infura-ipfs.io/ipfs/QmNjAMQ2uSmhoyjmcGsDj97VQLEMdTUsUt4fCxnmZAbJGk": GET https://lens.infura-ipfs.io/ipfs/QmNjAMQ2uSmhoyjmcGsDj97VQLEMdTUsUt4fCxnmZAbJGk giving up after 3 attempt(s)`

### PR DESCRIPTION
**Pull request by yondonfu**
Fixes https://github.com/livepeer/task-runner/issues/103

### CODE REVIEW

File: task/runner.go [hunk 1]
```diff
@@ -475,9 +475,17 @@ func errorInfo(err error) *data.ErrorInfo {
 func humanizeCatalystError(err error) error {
 	errMsg := strings.ToLower(err.Error())
 
+	fileNotAccessibleErrs := []string{
+		"504 Gateway Timeout",
+		"giving up after",
```
Comment (thomshutt) [inline task/runner.go:480]: I think we need a little more here, since there are a few places we do HTTP retries and this could happen for any of them

Comment (yondonfu) [reply task/runner.go:480]: Do you think this will be a problem even we filter for both "download error" and "import request" first as is done in [7ae097f](https://github.com/livepeer/task-runner/pull/104/commits/7ae097f62e9b46458f4205f6d81f21bfd4dabde1)?

At the moment, I'm not sure if there is a better way that doesn't involve restructuring catalyst-api error propagation, but I added a TODO and can create an issue to consider restructuring error propagation.

Comment (thomshutt) [reply task/runner.go:480]: You're right, I think that probably is enough - I'd missed the array was being used in combination with those

**Review by thomshutt — APPROVED** [review]

File: task/runner.go (hunk 1 above)
Comment (yondonfu) [reply task/runner.go:480]: Issue created https://github.com/livepeer/task-runner/issues/105

File: task/runner.go [hunk 2]
```diff
@@ -475,9 +475,19 @@ func errorInfo(err error) *data.ErrorInfo {
 func humanizeCatalystError(err error) error {
 	errMsg := strings.ToLower(err.Error())
 
+	fileNotAccessibleErrs := []string{
+		"504 Gateway Timeout",
```
Comment (victorges) [inline task/runner.go:479]: This needs to be lower case as well

File: task/runner.go [hunk 3]
```diff
@@ -475,9 +475,19 @@ func errorInfo(err error) *data.ErrorInfo {
...
+		"giving up after",
+	}
 	// General errors
-	if strings.Contains(errMsg, "import request") && strings.Contains(errMsg, "504 Gateway Timeout") {
-		return errors.New("file could not be imported from URL because it was not accessible")
+	// TODO(yondonfu): This string matching is ugly and we should come up with a better less error-prone way to
```
Comment (victorges) [inline task/runner.go:483]: Agreed. We should probably work with error codes like mediaconvert does (but may always have some string parsing fallback anyway, just hopefully won't be the main logic)
